Update smoke test command

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -417,37 +417,60 @@ jobs:
       #     stack_name: udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
 
   smoke-test:
-    working_directory: ~/project
     docker:
-      - image: cimg/node:13.13.0
+      # Lightweight Docker image
+      - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
-      - install_dependencies
+      - restore_cache:
+          keys: [backend-build]
       - attach_workspace:
           at: ~/
-      - restore_cache:
-          keys:
-            - frontend-build
-            - be-build--{{ .Revision  }}
       - run:
-          name: Get backend url
+          name: Install dependencies
           command: |
-            export BACKEND_IP=$(cat .circleci/ansible/inventory.txt | tail -n 1)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
+            # your code here
+            sudo apt-get update && sudo apt-get install -yy less
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
       - run:
           name: Backend smoke test.
-          command: chmod +x .circleci/scripts/smokeTest-BE.sh && .circleci/scripts/smokeTest-BE.sh
+          command: |
+            # your code here
+            export BACKEND_IP=$(aws ec2 describe-instances \
+            --query 'Reservations[*].Instances[*].PublicIpAddress' \
+            --filters Name=tag:aws:cloudformation:stack-name,Values=udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7} \
+            --output text)
+            echo $BACKEND_IP
+            export API_URL="http://${BACKEND_IP}:3030"
+            echo $API_URL
+            if curl "${API_URL}/api/status" | grep "ok"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      - restore_cache:
+          keys: [frontend-build]
       - run:
-          name: Frontend smoke test
-          command: chmod +x .circleci/scripts/smokeTest-FE.sh && .circleci/scripts/smokeTest-FE.sh $CIRCLE_WORKFLOW_ID
-      # - destroy-stack:
-      #     stack_name: udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}
-      # - delete_s3:
-      #     id: ${CIRCLE_WORKFLOW_ID:0:7}
-      # - destroy-stack:
-      #     stack_name: udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}
-      # - revert-migrations
+          name: Frontend smoke test.
+          command: |
+            # your code here
+            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"
+            echo $URL
+            if curl -s ${URL} | grep "Welcome"
+            then
+              exit 0
+            else
+              exit 1
+            fi
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      - revert-migrations:
+          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
 
   cloudfront-update:
     working_directory: ~/project
